name: Perspective
favicon: null
layout_spectrum: 0.9294085884466767
typography_spectrum: 0.11429020063951612
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8742889971472323
  lightness: 0.350983954500407
  saturation: 0.4580073419492692
  rhythmicContrast: 0.7023162404075265
purpose: []
